apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: catalog-service

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: catalog-service
  app.kubernetes.io/name: catalog-service
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: oficina-system

namespace: catalog-service
